package com.hsbc.fraud.model;

/**
 * Types of fraud alerts that can be generated by the detection system.
 */
public enum AlertType {
    HIGH_VALUE_TRANSACTION,       // Transaction exceeds threshold amount
    SUSPICIOUS_ACCOUNT,           // Transaction from/to suspicious account
    VELOCITY_BREACH,              // Too many transactions in short time
    GEOGRAPHIC_ANOMALY,           // Transaction from unusual location
    BLACKLISTED_MERCHANT,         // Transaction with blacklisted merchant
    UNUSUAL_PATTERN,              // Unusual transaction pattern detected
    CROSS_BORDER_SUSPICIOUS,      // Suspicious cross-border transaction
    TIME_BASED_ANOMALY,           // Transaction at unusual time
    DEVICE_ANOMALY,               // Transaction from unknown/suspicious device
    RAPID_SUCCESSIVE_TRANSACTIONS // Multiple rapid transactions
}

